"""empty message

Revision ID: 134af4b18185
Revises: 17c9969081a4
Create Date: 2022-06-26 21:41:52.711428

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '134af4b18185'
down_revision = '17c9969081a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('movie_renter_detail_mrtd_mrth_id_fkey', 'movie_renter_detail', type_='foreignkey')
    op.drop_constraint('movie_renter_detail_mrtd_mvd_id_fkey', 'movie_renter_detail', type_='foreignkey')
    op.alter_column('user_on_ban', 'uob_release_date',
               existing_type=sa.DATE(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_on_ban', 'uob_release_date',
               existing_type=sa.DATE(),
               nullable=True)
    op.create_foreign_key('movie_renter_detail_mrtd_mvd_id_fkey', 'movie_renter_detail', 'ms_movie_dvds', ['mrtd_mvd_id'], ['mvd_id'])
    op.create_foreign_key('movie_renter_detail_mrtd_mrth_id_fkey', 'movie_renter_detail', 'movie_renter_head', ['mrtd_mrth_id'], ['mrth_id'])
    # ### end Alembic commands ###
