"""empty message

Revision ID: 17c9969081a4
Revises: 748becb3e95c
Create Date: 2022-06-26 18:22:25.701121

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17c9969081a4'
down_revision = '748becb3e95c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_on_ban', 'uob_release_date',
               existing_type=sa.DATE(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_on_ban', 'uob_release_date',
               existing_type=sa.DATE(),
               nullable=False)
    # ### end Alembic commands ###
