"""empty message

Revision ID: 1edd3f017294
Revises: 754b3db9356b
Create Date: 2022-06-27 07:56:50.581835

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1edd3f017294'
down_revision = '754b3db9356b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_alert',
    sa.Column('al_id', sa.Integer(), nullable=False),
    sa.Column('al_read_status', sa.String(length=1), nullable=False),
    sa.Column('msa_create_date', sa.Date(), nullable=True),
    sa.Column('msa_create_user', sa.String(length=30), nullable=True),
    sa.Column('msa_update_date', sa.Date(), nullable=True),
    sa.Column('msa_update_user', sa.String(length=30), nullable=True),
    sa.PrimaryKeyConstraint('al_id'),
    sa.UniqueConstraint('al_read_status')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_alert')
    # ### end Alembic commands ###
