"""empty message

Revision ID: 2dd8d1b09ee5
Revises: aaf78aae1ec5
Create Date: 2022-06-27 11:09:54.944958

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2dd8d1b09ee5'
down_revision = 'aaf78aae1ec5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ms_movie_dvds', sa.Column('mvd_on_air_status', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ms_movie_dvds', 'mvd_on_air_status')
    # ### end Alembic commands ###
