"""empty message

Revision ID: 419046db5269
Revises: 7f32a97b972a
Create Date: 2022-06-26 17:59:40.868853

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '419046db5269'
down_revision = '7f32a97b972a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ms_user', sa.Column('msu_banned_status', sa.String(length=2), nullable=True))
    op.drop_column('user_on_ban', 'uob_status')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_on_ban', sa.Column('uob_status', sa.VARCHAR(length=1), autoincrement=False, nullable=False))
    op.drop_column('ms_user', 'msu_banned_status')
    # ### end Alembic commands ###
