"""empty message

Revision ID: 4be42a546568
Revises: dc97a8497925
Create Date: 2022-06-26 17:40:23.887433

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4be42a546568'
down_revision = 'dc97a8497925'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_on_ban', sa.Column('uob_release_date', sa.Date(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_on_ban', 'uob_release_date')
    # ### end Alembic commands ###
