"""empty message

Revision ID: 50853c252ad9
Revises: c5da2668dd92
Create Date: 2022-06-25 11:28:48.747862

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50853c252ad9'
down_revision = 'c5da2668dd92'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('movie_rental_head',
    sa.Column('mrth_id', sa.Integer(), nullable=False),
    sa.Column('mrth_msu_id', sa.Integer(), nullable=False),
    sa.Column('mrth_rent_start_date', sa.Date(), nullable=False),
    sa.Column('mrth_rent_due_date', sa.Date(), nullable=False),
    sa.Column('mrth_rent_duration', sa.Integer(), nullable=True),
    sa.Column('mrth_shipping_destination', sa.String(length=500), nullable=False),
    sa.Column('mrth_create_date', sa.Date(), nullable=True),
    sa.Column('mrth_create_user', sa.String(length=30), nullable=True),
    sa.Column('mrth_update_date', sa.Date(), nullable=True),
    sa.Column('mrth_update_user', sa.String(length=30), nullable=True),
    sa.PrimaryKeyConstraint('mrth_id')
    )
    op.create_table('movie_reviews',
    sa.Column('mr_mvd_id', sa.Integer(), nullable=False),
    sa.Column('mr_msu_id', sa.Integer(), nullable=False),
    sa.Column('mr_desc', sa.String(length=500), nullable=True),
    sa.Column('mr_rate', sa.Integer(), nullable=False),
    sa.Column('mr_create_date', sa.Date(), nullable=True),
    sa.Column('mr_create_user', sa.String(length=30), nullable=True),
    sa.Column('mr_update_date', sa.Date(), nullable=True),
    sa.Column('mr_update_user', sa.String(length=30), nullable=True),
    sa.PrimaryKeyConstraint('mr_mvd_id')
    )
    op.create_table('ms_movie_dvds',
    sa.Column('mvd_id', sa.Integer(), nullable=False),
    sa.Column('mvd_desc', sa.String(length=500), nullable=False),
    sa.Column('mvd_release_date', sa.Date(), nullable=False),
    sa.Column('mvd_age_certification', sa.Integer(), nullable=False),
    sa.Column('mvd_genre', sa.String(length=50), nullable=False),
    sa.Column('mvd_total_dvds', sa.Integer(), nullable=False),
    sa.Column('mvd_available_stock', sa.Integer(), nullable=False),
    sa.Column('mvd_image_path', sa.String(length=200), nullable=True),
    sa.Column('mvd_create_date', sa.Date(), nullable=True),
    sa.Column('mvd_create_user', sa.String(length=30), nullable=True),
    sa.Column('mvd_update_date', sa.Date(), nullable=True),
    sa.Column('mvd_update_user', sa.String(length=30), nullable=True),
    sa.PrimaryKeyConstraint('mvd_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ms_movie_dvds')
    op.drop_table('movie_reviews')
    op.drop_table('movie_rental_head')
    # ### end Alembic commands ###
