"""empty message

Revision ID: 519f92404df5
Revises: 
Create Date: 2022-06-25 10:55:57.641247

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '519f92404df5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ms_user',
    sa.Column('msu_id', sa.Integer(), nullable=False),
    sa.Column('msu_email', sa.String(length=50), nullable=False),
    sa.Column('msu_password', sa.String(length=100), nullable=False),
    sa.Column('msu_name', sa.String(length=100), nullable=False),
    sa.Column('msu_address', sa.String(length=200), nullable=False),
    sa.Column('msu_gender', sa.String(length=1), nullable=False),
    sa.Column('msu_birth_date', sa.Date(), nullable=False),
    sa.Column('msu_create_date', sa.Date(), nullable=True),
    sa.Column('msu_create_user', sa.String(length=30), nullable=True),
    sa.Column('msu_update_date', sa.Date(), nullable=True),
    sa.Column('msu_update_user', sa.String(length=30), nullable=True),
    sa.PrimaryKeyConstraint('msu_id'),
    sa.UniqueConstraint('msu_email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ms_user')
    # ### end Alembic commands ###
