"""empty message

Revision ID: 748008e95d19
Revises: f9d93c53022d
Create Date: 2022-06-25 14:12:07.363219

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '748008e95d19'
down_revision = 'f9d93c53022d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ms_admin',
    sa.Column('msa_id', sa.Integer(), nullable=False),
    sa.Column('msa_email', sa.String(length=50), nullable=False),
    sa.Column('msa_password', sa.String(length=100), nullable=False),
    sa.Column('msa_name', sa.String(length=100), nullable=False),
    sa.Column('msa_active_status', sa.String(length=1), nullable=False),
    sa.Column('msa_create_date', sa.Date(), nullable=True),
    sa.Column('msa_create_user', sa.String(length=30), nullable=True),
    sa.Column('msa_update_date', sa.Date(), nullable=True),
    sa.Column('msa_update_user', sa.String(length=30), nullable=True),
    sa.PrimaryKeyConstraint('msa_id'),
    sa.UniqueConstraint('msa_email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ms_admin')
    # ### end Alembic commands ###
