"""empty message

Revision ID: 754b3db9356b
Revises: a0313acf5a5f
Create Date: 2022-06-27 00:46:15.832918

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '754b3db9356b'
down_revision = 'a0313acf5a5f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'movie_renter_detail', 'ms_movie_dvds', ['mrtd_mvd_id'], ['mvd_id'])
    op.create_foreign_key(None, 'movie_renter_detail', 'movie_renter_head', ['mrtd_mrth_id'], ['mrth_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'movie_renter_detail', type_='foreignkey')
    op.drop_constraint(None, 'movie_renter_detail', type_='foreignkey')
    # ### end Alembic commands ###
