"""empty message

Revision ID: 7f32a97b972a
Revises: 4be42a546568
Create Date: 2022-06-26 17:57:52.908328

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f32a97b972a'
down_revision = '4be42a546568'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ms_user', sa.Column('msu_banned_status', sa.String(length=1), nullable=False))
    op.drop_column('user_on_ban', 'uob_status')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_on_ban', sa.Column('uob_status', sa.VARCHAR(length=1), autoincrement=False, nullable=False))
    op.drop_column('ms_user', 'msu_banned_status')
    # ### end Alembic commands ###
