"""empty message

Revision ID: 8620f414b1e3
Revises: c3f495ece122
Create Date: 2022-06-25 12:14:18.663397

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8620f414b1e3'
down_revision = 'c3f495ece122'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courier', sa.Column('msc_create_date', sa.Date(), nullable=True))
    op.add_column('courier', sa.Column('msc_create_user', sa.String(length=30), nullable=True))
    op.add_column('courier', sa.Column('msc_update_date', sa.Date(), nullable=True))
    op.add_column('courier', sa.Column('msc_update_user', sa.String(length=30), nullable=True))
    op.drop_column('courier', 'ri_update_user')
    op.drop_column('courier', 'ri_update_date')
    op.drop_column('courier', 'ri_create_user')
    op.drop_column('courier', 'ri_create_date')
    op.create_foreign_key(None, 'user_on_ban', 'ms_user', ['uob_msu_id'], ['msu_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_on_ban', type_='foreignkey')
    op.add_column('courier', sa.Column('ri_create_date', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('courier', sa.Column('ri_create_user', sa.VARCHAR(length=30), autoincrement=False, nullable=True))
    op.add_column('courier', sa.Column('ri_update_date', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('courier', sa.Column('ri_update_user', sa.VARCHAR(length=30), autoincrement=False, nullable=True))
    op.drop_column('courier', 'msc_update_user')
    op.drop_column('courier', 'msc_update_date')
    op.drop_column('courier', 'msc_create_user')
    op.drop_column('courier', 'msc_create_date')
    # ### end Alembic commands ###
