"""empty message

Revision ID: a6e85938c937
Revises: d5747c3e8b7a
Create Date: 2022-06-25 13:16:50.772771

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a6e85938c937'
down_revision = 'd5747c3e8b7a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ms_courier',
    sa.Column('msc_id', sa.Integer(), nullable=False),
    sa.Column('msc_desc', sa.String(length=100), nullable=False),
    sa.Column('msc_active_status', sa.String(length=1), nullable=False),
    sa.Column('msc_create_date', sa.Date(), nullable=True),
    sa.Column('msc_create_user', sa.String(length=30), nullable=True),
    sa.Column('msc_update_date', sa.Date(), nullable=True),
    sa.Column('msc_update_user', sa.String(length=30), nullable=True),
    sa.PrimaryKeyConstraint('msc_id')
    )
    op.create_table('movie_renter_head',
    sa.Column('mrth_id', sa.Integer(), nullable=False),
    sa.Column('mrth_msu_id', sa.Integer(), nullable=False),
    sa.Column('mrth_rent_start_date', sa.Date(), nullable=False),
    sa.Column('mrth_rent_due_date', sa.Date(), nullable=False),
    sa.Column('mrth_rent_duration', sa.Integer(), nullable=True),
    sa.Column('mrth_shipping_destination', sa.String(length=500), nullable=False),
    sa.Column('mrth_create_date', sa.Date(), nullable=True),
    sa.Column('mrth_create_user', sa.String(length=30), nullable=True),
    sa.Column('mrth_update_date', sa.Date(), nullable=True),
    sa.Column('mrth_update_user', sa.String(length=30), nullable=True),
    sa.ForeignKeyConstraint(['mrth_msu_id'], ['ms_user.msu_id'], ),
    sa.PrimaryKeyConstraint('mrth_id')
    )
    op.create_table('dvds_shipment',
    sa.Column('dsp_id', sa.Integer(), nullable=False),
    sa.Column('dsp_msc_id', sa.Integer(), nullable=False),
    sa.Column('dsp_mrth_id', sa.Integer(), nullable=False),
    sa.Column('dsp_mrth_shipping_destination', sa.String(length=500), nullable=False),
    sa.Column('dsp_shipping_status', sa.String(length=20), nullable=True),
    sa.Column('dsp_received_date', sa.Date(), nullable=True),
    sa.Column('dsp_create_date', sa.Date(), nullable=True),
    sa.Column('dsp_create_user', sa.String(length=30), nullable=True),
    sa.Column('dsp_update_date', sa.Date(), nullable=True),
    sa.Column('dsp_update_user', sa.String(length=30), nullable=True),
    sa.ForeignKeyConstraint(['dsp_mrth_id'], ['movie_renter_head.mrth_id'], ),
    sa.ForeignKeyConstraint(['dsp_msc_id'], ['ms_courier.msc_id'], ),
    sa.PrimaryKeyConstraint('dsp_id')
    )
    op.create_table('movie_renter_detail',
    sa.Column('mrtd_mvd_id', sa.Integer(), nullable=False),
    sa.Column('mrtd_mrth_id', sa.Integer(), nullable=False),
    sa.Column('mrtd_create_date', sa.Date(), nullable=True),
    sa.Column('mrtd_create_user', sa.String(length=30), nullable=True),
    sa.Column('mrtd_update_date', sa.Date(), nullable=True),
    sa.Column('mrtd_update_user', sa.String(length=30), nullable=True),
    sa.ForeignKeyConstraint(['mrtd_mrth_id'], ['movie_renter_head.mrth_id'], ),
    sa.ForeignKeyConstraint(['mrtd_mvd_id'], ['ms_movie_dvds.mvd_id'], ),
    sa.PrimaryKeyConstraint('mrtd_mvd_id', 'mrtd_mrth_id')
    )
    op.drop_table('renter_shipment')
    op.drop_table('courier')
    op.drop_table('movie_rental_detail')
    op.drop_table('movie_rental_head')
    op.create_foreign_key(None, 'movie_returned_detail', 'movie_returned_head', ['mrd_mrh_id'], ['mrh_id'])
    op.create_foreign_key(None, 'movie_returned_detail', 'ms_movie_dvds', ['mrd_mvd_id'], ['mvd_id'])
    op.create_foreign_key(None, 'movie_returned_head', 'movie_renter_head', ['mrh_mrth_id'], ['mrth_id'])
    op.create_foreign_key(None, 'movie_returned_head', 'ms_user', ['mrh_mrth_msu_id'], ['msu_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'movie_returned_head', type_='foreignkey')
    op.drop_constraint(None, 'movie_returned_head', type_='foreignkey')
    op.drop_constraint(None, 'movie_returned_detail', type_='foreignkey')
    op.drop_constraint(None, 'movie_returned_detail', type_='foreignkey')
    op.create_table('movie_rental_head',
    sa.Column('mrth_id', sa.INTEGER(), server_default=sa.text("nextval('movie_rental_head_mrth_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('mrth_msu_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('mrth_rent_start_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('mrth_rent_due_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('mrth_rent_duration', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('mrth_shipping_destination', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('mrth_create_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('mrth_create_user', sa.VARCHAR(length=30), autoincrement=False, nullable=True),
    sa.Column('mrth_update_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('mrth_update_user', sa.VARCHAR(length=30), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['mrth_msu_id'], ['ms_user.msu_id'], name='movie_rental_head_mrth_msu_id_fkey'),
    sa.PrimaryKeyConstraint('mrth_id', name='movie_rental_head_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('movie_rental_detail',
    sa.Column('mrtd_mvd_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('mrtd_mrth_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('mrtd_create_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('mrtd_create_user', sa.VARCHAR(length=30), autoincrement=False, nullable=True),
    sa.Column('mrtd_update_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('mrtd_update_user', sa.VARCHAR(length=30), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['mrtd_mrth_id'], ['movie_rental_head.mrth_id'], name='movie_rental_detail_mrtd_mrth_id_fkey'),
    sa.ForeignKeyConstraint(['mrtd_mvd_id'], ['ms_movie_dvds.mvd_id'], name='movie_rental_detail_mrtd_mvd_id_fkey'),
    sa.PrimaryKeyConstraint('mrtd_mvd_id', name='movie_rental_detail_pkey')
    )
    op.create_table('courier',
    sa.Column('msc_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('msc_desc', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('msc_active_status', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('msc_create_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('msc_create_user', sa.VARCHAR(length=30), autoincrement=False, nullable=True),
    sa.Column('msc_update_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('msc_update_user', sa.VARCHAR(length=30), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('msc_id', name='courier_pkey')
    )
    op.create_table('renter_shipment',
    sa.Column('dsp_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('dsp_msc_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('dsp_mrth_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('dsp_mrth_shipping_destination', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('dsp_shipping_status', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('dsp_received_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('dsp_create_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('dsp_create_user', sa.VARCHAR(length=30), autoincrement=False, nullable=True),
    sa.Column('dsp_update_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('dsp_update_user', sa.VARCHAR(length=30), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('dsp_id', name='renter_shipment_pkey')
    )
    op.drop_table('movie_renter_detail')
    op.drop_table('dvds_shipment')
    op.drop_table('movie_renter_head')
    op.drop_table('ms_courier')
    # ### end Alembic commands ###
