"""empty message

Revision ID: a85db677766e
Revises: e125755ce91d
Create Date: 2022-06-28 10:10:45.402235

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a85db677766e'
down_revision = 'e125755ce91d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_alert', sa.Column('al_desc', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_alert', 'al_desc')
    # ### end Alembic commands ###
