"""empty message

Revision ID: aaf78aae1ec5
Revises: c3f46dcec005
Create Date: 2022-06-27 08:23:32.700484

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aaf78aae1ec5'
down_revision = 'c3f46dcec005'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_alert', sa.Column('al_create_date', sa.Date(), nullable=True))
    op.add_column('user_alert', sa.Column('al_create_user', sa.String(length=30), nullable=True))
    op.add_column('user_alert', sa.Column('al_update_date', sa.Date(), nullable=True))
    op.add_column('user_alert', sa.Column('al_update_user', sa.String(length=30), nullable=True))
    op.drop_column('user_alert', 'al_desc')
    op.drop_column('user_alert', 'msa_create_user')
    op.drop_column('user_alert', 'msa_create_date')
    op.drop_column('user_alert', 'msa_update_date')
    op.drop_column('user_alert', 'msa_update_user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_alert', sa.Column('msa_update_user', sa.VARCHAR(length=30), autoincrement=False, nullable=True))
    op.add_column('user_alert', sa.Column('msa_update_date', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('user_alert', sa.Column('msa_create_date', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('user_alert', sa.Column('msa_create_user', sa.VARCHAR(length=30), autoincrement=False, nullable=True))
    op.add_column('user_alert', sa.Column('al_desc', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.drop_column('user_alert', 'al_update_user')
    op.drop_column('user_alert', 'al_update_date')
    op.drop_column('user_alert', 'al_create_user')
    op.drop_column('user_alert', 'al_create_date')
    # ### end Alembic commands ###
