"""empty message

Revision ID: bc6f88f8d144
Revises: 1edd3f017294
Create Date: 2022-06-27 08:15:52.448299

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc6f88f8d144'
down_revision = '1edd3f017294'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_alert', sa.Column('al_desc', sa.String(length=500), nullable=True))
    op.alter_column('user_alert', 'al_read_status',
               existing_type=sa.VARCHAR(length=1),
               nullable=True)
    op.drop_constraint('user_alert_al_read_status_key', 'user_alert', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('user_alert_al_read_status_key', 'user_alert', ['al_read_status'])
    op.alter_column('user_alert', 'al_read_status',
               existing_type=sa.VARCHAR(length=1),
               nullable=False)
    op.drop_column('user_alert', 'al_desc')
    # ### end Alembic commands ###
