"""empty message

Revision ID: c25c5fecbb0d
Revises: 0048ef31b598
Create Date: 2022-06-25 12:01:02.471089

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c25c5fecbb0d'
down_revision = '0048ef31b598'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('renter_invoices',
    sa.Column('ri_id', sa.Integer(), nullable=False),
    sa.Column('ri_mrth_id', sa.Integer(), nullable=False),
    sa.Column('ri_nominal', sa.Integer(), nullable=False),
    sa.Column('ri_status_bayar', sa.String(length=1), nullable=False),
    sa.Column('ri_bukti_bayar', sa.String(length=200), nullable=True),
    sa.Column('ri_transaction_date', sa.Date(), nullable=True),
    sa.Column('ri_transaction_validation_date', sa.Date(), nullable=True),
    sa.Column('ri_create_date', sa.Date(), nullable=True),
    sa.Column('ri_create_user', sa.String(length=30), nullable=True),
    sa.Column('ri_update_date', sa.Date(), nullable=True),
    sa.Column('ri_update_user', sa.String(length=30), nullable=True),
    sa.PrimaryKeyConstraint('ri_id')
    )
    op.create_table('renter_shipment',
    sa.Column('dsp_id', sa.Integer(), nullable=False),
    sa.Column('dsp_msc_id', sa.Integer(), nullable=False),
    sa.Column('dsp_mrth_id', sa.Integer(), nullable=False),
    sa.Column('dsp_mrth_shipping_destination', sa.String(length=500), nullable=False),
    sa.Column('dsp_shipping_status', sa.Date(), nullable=True),
    sa.Column('dsp_received_date', sa.Date(), nullable=True),
    sa.Column('dsp_create_date', sa.Date(), nullable=True),
    sa.Column('dsp_create_user', sa.String(length=30), nullable=True),
    sa.Column('dsp_update_date', sa.Date(), nullable=True),
    sa.Column('dsp_update_user', sa.String(length=30), nullable=True),
    sa.PrimaryKeyConstraint('dsp_id')
    )
    op.add_column('movie_reviews', sa.Column('mr_active_status', sa.String(length=1), nullable=False))
    op.add_column('ms_movie_dvds', sa.Column('mvd_active_status', sa.String(length=1), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ms_movie_dvds', 'mvd_active_status')
    op.drop_column('movie_reviews', 'mr_active_status')
    op.drop_table('renter_shipment')
    op.drop_table('renter_invoices')
    # ### end Alembic commands ###
