"""empty message

Revision ID: c3f46dcec005
Revises: bc6f88f8d144
Create Date: 2022-06-27 08:16:42.784926

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c3f46dcec005'
down_revision = 'bc6f88f8d144'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_alert', sa.Column('al_msu_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_alert', 'al_msu_id')
    # ### end Alembic commands ###
