"""empty message

Revision ID: d1d8209cb59b
Revises: 8620f414b1e3
Create Date: 2022-06-25 12:26:49.097033

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd1d8209cb59b'
down_revision = '8620f414b1e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'movie_reviews', 'ms_user', ['mr_msu_id'], ['msu_id'])
    op.create_foreign_key(None, 'movie_reviews', 'ms_movie_dvds', ['mr_mvd_id'], ['mvd_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'movie_reviews', type_='foreignkey')
    op.drop_constraint(None, 'movie_reviews', type_='foreignkey')
    # ### end Alembic commands ###
