"""empty message

Revision ID: d5747c3e8b7a
Revises: d1d8209cb59b
Create Date: 2022-06-25 12:53:19.842470

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd5747c3e8b7a'
down_revision = 'd1d8209cb59b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'movie_rental_detail', 'movie_rental_head', ['mrtd_mrth_id'], ['mrth_id'])
    op.create_foreign_key(None, 'movie_rental_detail', 'ms_movie_dvds', ['mrtd_mvd_id'], ['mvd_id'])
    op.create_foreign_key(None, 'movie_rental_head', 'ms_user', ['mrth_msu_id'], ['msu_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'movie_rental_head', type_='foreignkey')
    op.drop_constraint(None, 'movie_rental_detail', type_='foreignkey')
    op.drop_constraint(None, 'movie_rental_detail', type_='foreignkey')
    # ### end Alembic commands ###
