"""empty message

Revision ID: dc97a8497925
Revises: 748008e95d19
Create Date: 2022-06-25 17:05:46.987143

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc97a8497925'
down_revision = '748008e95d19'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ms_movie_dvds', sa.Column('mvd_title', sa.String(length=200), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ms_movie_dvds', 'mvd_title')
    # ### end Alembic commands ###
