"""empty message

Revision ID: e125755ce91d
Revises: 2dd8d1b09ee5
Create Date: 2022-06-27 15:06:09.863469

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e125755ce91d'
down_revision = '2dd8d1b09ee5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ms_movie_dvds', sa.Column('mvd_price', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ms_movie_dvds', 'mvd_price')
    # ### end Alembic commands ###
