"""empty message

Revision ID: f9d93c53022d
Revises: a6e85938c937
Create Date: 2022-06-25 13:25:56.300897

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9d93c53022d'
down_revision = 'a6e85938c937'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'renter_invoices', 'movie_renter_head', ['ri_mrth_id'], ['mrth_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'renter_invoices', type_='foreignkey')
    # ### end Alembic commands ###
