"""empty message

Revision ID: fe2f72af098d
Revises: a85db677766e
Create Date: 2022-06-28 11:27:44.220361

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe2f72af098d'
down_revision = 'a85db677766e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_alert', sa.Column('al_title', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_alert', 'al_title')
    # ### end Alembic commands ###
